from turtle import*

# Draw filled square
def fillSquare(length):
    down()
    begin_fill()
    for i in range(4):
        forward(length)
        right(90)

    end_fill()
    up()

# Draw filled Star
def fillStar():
    pensize(2)
    down()
    begin_fill()
    for i in range(5):
        forward(30)
        right(144)
    end_fill()
    up()

# Draw filled Circle
def fillCircle(data):
    for spot in data:
        setposition(spot[0],spot[1])
        down()
        begin_fill()
        circle(spot[2])
        end_fill()
        up()

# Create the picture
def drawMaze():
    setup(675,580)
    speed('fastest')
    bgcolor('light blue')
    up()
    setposition(-300,250)
    color('blue')
    fillSquare(25)
    setposition(-275, 275)
    down()
    pensize(10)
    circle(-50,100)
    up()
    circle(-50, 50)
    down()
    circle(-50,230)
    up()
    setposition(-200,250)
    color('purple')
    fillStar()
    setposition(-300,-250)
    color('orange')
    fillStar()
    color('white')
    data=[[-300,-225,15],[-325,-200,10],[-225,-250,50],[-200,-275,10]]
    fillCircle(data)
    color('green')
    setposition(300,200)
    fillStar()
    color('red')
    setposition(100,300)
    seth(270)
    down()
    forward(150)
    up()
    forward(40)
    down()
    forward(110)
    up()
    setposition(150,300)
    seth(270)
    down()
    forward(75)
    up()
    forward(40)
    down()
    forward(185)
    up()
    setposition(200,300)
    seth(270)
    down()
    forward(185)
    up()
    forward(40)
    down()
    forward(75)
    up()
    setposition(250,300)
    seth(270)
    up()
    forward(50)
    down()
    forward(250)
    up()
    setposition(100,0)
    down()
    seth(0)
    forward(300)

    # Restore turtle for students to draw
    up()
    setposition(-300,250)
    color('black')
    speed(6)
    pensize(1)
    down()
